name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test with (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [3.1, 3.2, 3.3, 3.4]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install

      - name: Run test
        run: rake
